/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentList: typeof import('./components/ContentList.vue')['default']
    DiffCodes: typeof import('./components/DiffCodes.vue')['default']
    HoverCard: typeof import('./components/HoverCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    WrapperPost: typeof import('./components/WrapperPost.vue')['default']
  }
}
